### ISSUE TITLE
Shows bad update message

### ISSUE THREAD

**Issue by charliegroll** [SamVerschueren/alfred-notifier#10]
![screenshot](https://user-images.githubusercontent.com/1126370/88240856-68756800-cc56-11ea-9721-8a90bc816b21.png)

Alfred v4.1, freshly installed via `npm i -g alfred-jira` today, so `alfy@0.9.1` and `alfred-notifier@0.2.3`

https://github.com/colinf/alfred-jira for workflow reference

**Comment by SamVerschueren** [comment]
This is an issue on their side. See this line over here https://github.com/colinf/alfred-jira/blob/master/info.plist#L76. They have to remove that text. So it would be best to send them a PR fixing this.
