### ISSUE TITLE
Unref the child process

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/alfred-notifier#6]
I'm not sure if this would benefit performance or something, but I don't think it could hurt either. A new child process is being created in order to check for updates right [here](https://github.com/SamVerschueren/alfred-notifier/blob/master/index.js#L6).

@sindresorhus Any reasons why we shouldn't do this?

```js
const cp = execa(path.join(__dirname, 'check.js'));
cp.unref();
```

**Comment by sindresorhus** [comment]
> I'm not sure if this would benefit performance or something, but I don't think it could hurt either.

In some cases the child process can prevent the parent process from exiting until it's done. In those cases it can help.

> Any reasons why we shouldn't do this?

You lose out of error handling if the update process throws after it's been unref'd, but I don't think that's a big problem.

**Comment by SamVerschueren** [comment]
> but I don't think that's a big problem.

Not in this case. I don't care if it fails, it will rerun the next time. It shouldn't get in the way of Alfred.

**Comment by SamVerschueren** [comment]
Reopening since this wasn't fixed by the previous commit.
